### PR TITLE
s1024803-2

### PR DESCRIPTION
**Pull request by jack8102060**

### CODE REVIEW

**Comment by jrjang2** [comment]
There is a conflict now. Please solve this issue before doing pull request. Update this pull request instead of closing this. If you have any questions, you can ask here.

Tip:
1. Fork this project (jrjang2/lab) again to obtain the last git tree.
2. Update (```git pull --rebase```) your working directory.
3. Fix conflict and commit.
4. pull request.

**Comment by jack8102060** [comment]
done[image: 內置圖片 1]

2015-11-11 20:47 GMT+08:00 jrjang2 <notifications@github.com>:

**Comment by jrjang2** [comment]
Good. There is a conflict now. Please solve this issue before doing pull request. Update this pull request instead of closing this. If you have any questions, you can ask here.

Tip:
1. Fork this project (jrjang2/lab) again to obtain the last git tree.
2. Update (```git pull --rebase```) your working directory.
3. Fix conflict and commit.
4. pull request.

**Comment by jack8102060** [comment]
done[image: 內置圖片 1]

2015-11-11 21:19 GMT+08:00 jrjang2 <notifications@github.com>:

**Comment by jack8102060** [comment]
[image: 內置圖片 2]

2015-11-11 22:02 GMT+08:00 Jia-Jing Chang <jack8102060@gmail.com>:

**Comment by jrjang2** [comment]
Good. But there is a conflict now. Please solve this issue before doing pull request. Update this pull request instead of closing this. If you have any questions, you can ask here.

Tip:
1. Fork this project (jrjang2/lab) again to obtain the last git tree.
2. Update (```git pull --rebase```) your working directory.
3. Fix conflict and commit.
4. pull request.

**Pull request closed without merging**
